export const POSTHOG_PROJECT_API_KEY =
  process.env.NEXT_PUBLIC_POSTHOG_PROJECT_API_KEY;
export const POSTHOG_API_HOST = process.env.NEXT_PUBLIC_POSTHOG_API_HOST;
export const POSTHOG_UI_HOST = process.env.NEXT_PUBLIC_POSTHOG_UI_HOST;
